spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      # 设置不参与热部署的文件或文件夹
      exclude: public/**,config/application.yml
server:
  port: 8080
amap:
  key: 9c7f97e95b93948af40ddab4871ffa18
